---
# TODO: Define variables in host inventory

- hosts: shippers
  become: yes
  gather_facts: yes

  roles:
    - { role: ansible-role-nginx, http_port: 80 }
    - { role: ansible-role-filebeat, filebeat_output_logstash_hosts: "192.168.50.12:5044" }

- hosts: logstash
  become: yes
  gather_facts: yes

  roles:
    - { role: ansible-role-nginx, http_port: 80 }
    - { role: geerlingguy.java }
    - { role: ansible-role-logstash, logstash_listen_port_beats: 5044, logstash_elasticsearch_hosts: "http://192.168.50.11:9200" }

- hosts: kibana
  become: yes
  gather_facts: yes

  roles:
    - { role: ansible-role-kibana, kibana_server_port: 5601, kibana_server_host: "192.168.50.10", kibana_elasticsearch_url: "http://192.168.50.11:9200" }

- hosts: elastic
  become: yes
  gather_facts: yes

  roles:
    - { role: ansible-role-nginx, http_port: 80 }
    - { role: geerlingguy.java }
    - { role: ansible-role-elasticsearch, elasticsearch_network_host: 192.168.50.11, elasticsearch_http_port: 9200 }