---
# TODO: Define variables in host inventory

- hosts: shippers
  become: yes
  gather_facts: yes
  vars:
    filebeat_output_logstash_enabled: true
    filebeat_output_logstash_hosts: "192.168.50.12:5044"

  roles:
    - ansible-role-nginx
    - ansible-role-filebeat

- hosts: logstash
  become: yes
  gather_facts: yes

  vars:
    logstash_listen_port_beats: 5044
    logstash_elasticsearch_hosts: http://192.168.50.11:9200

  roles:
    - ansible-role-nginx
    - geerlingguy.java
    - ansible-role-logstash

- hosts: kibana
  become: yes
  gather_facts: yes

  vars:
    kibana_server_port: 5601
    kibana_server_host: "192.168.50.10"
    kibana_elasticsearch_url: "http://192.168.50.11:9200"

  roles:
    - ansible-role-kibana

- hosts: elastic
  become: yes
  gather_facts: yes

  vars:
    elasticsearch_network_host: 192.168.50.11
    elasticsearch_http_port: 9200

  roles:
    - ansible-role-nginx
    - geerlingguy.java
    - ansible-role-elasticsearch